import { Question } from "./concursos";

const q = (
  id: string,
  disciplina: string,
  enunciado: string,
  opcoes: string[],
  correta: number,
  comentario: string,
): Question => ({ id, disciplina, enunciado, opcoes, correta, comentario });

// =========================================================
// ENFERMEIRO – 50 questões
// =========================================================
export const bancoEnfermeiro: Question[] = [
  q("enf1", "Fundamentos de Enfermagem", "Qual a sequência correcta da lavagem das mãos segundo a OMS?",
    ["Molhar, ensaboar, esfregar, enxaguar, secar", "Ensaboar, molhar, enxaguar, secar", "Molhar, enxaguar, ensaboar, secar", "Esfregar, molhar, secar, ensaboar"], 0,
    "A OMS define: molhar, aplicar sabão, esfregar todas as superfícies por 40-60s, enxaguar e secar."),
  q("enf2", "Saúde Materno-Infantil", "Número mínimo de consultas pré-natais recomendado pela OMS (2016) e adoptado pelo MINSA?",
    ["2", "4", "6", "8"], 3,
    "A OMS passou a recomendar no mínimo 8 contactos pré-natais para reduzir mortalidade materna e perinatal."),
  q("enf3", "Emergências", "No protocolo de RCP em adulto, a relação compressões/ventilações é:",
    ["15:2", "30:2", "5:1", "10:2"], 1,
    "Para adultos, 30 compressões para 2 ventilações, segundo directrizes AHA/ERC."),
  q("enf4", "Ética", "O sigilo profissional do enfermeiro pode ser quebrado:",
    ["Nunca", "Por ordem judicial ou risco grave", "Sempre que solicitado", "Apenas para familiares"], 1,
    "Só pode ser quebrado por ordem judicial ou risco grave para o próprio ou terceiros."),
  q("enf5", "Saúde Materno-Infantil", "A amamentação exclusiva deve ocorrer até aos:",
    ["3 meses", "6 meses", "9 meses", "12 meses"], 1,
    "OMS e MINSA recomendam aleitamento materno exclusivo até aos 6 meses."),
  q("enf6", "Fundamentos de Enfermagem", "Os cinco certos da administração de medicamentos incluem:",
    ["Paciente, medicamento, dose, via, hora", "Paciente, médico, dose, via, hora", "Médico, medicamento, dose, via, hora", "Paciente, medicamento, marca, via, sala"], 0,
    "Os 5 certos: paciente, medicamento, dose, via e hora correctos."),
  q("enf7", "Emergências", "A frequência de compressões torácicas na RCP do adulto é de:",
    ["60-80/min", "80-100/min", "100-120/min", "140-160/min"], 2,
    "AHA recomenda 100 a 120 compressões por minuto, com profundidade de 5-6 cm."),
  q("enf8", "Saúde Pública", "A dengue é transmitida principalmente pelo vector:",
    ["Anopheles", "Aedes aegypti", "Culex", "Glossina"], 1,
    "Aedes aegypti é o principal vector da dengue, zika e chikungunya."),
  q("enf9", "Fundamentos de Enfermagem", "Sinais vitais incluem todos, EXCEPTO:",
    ["Temperatura", "Pulso", "Diurese", "Tensão arterial"], 2,
    "Sinais vitais clássicos: TA, FC, FR e temperatura. Diurese é parâmetro de eliminação."),
  q("enf10", "Saúde Materno-Infantil", "A cartão da grávida em Angola deve ser preenchido a partir de:",
    ["3.º trimestre", "Confirmação da gravidez", "Quando há sintomas", "Após o parto"], 1,
    "O cartão deve ser aberto na primeira consulta pré-natal, logo após confirmação."),
  q("enf11", "Farmacologia", "Adrenalina em paragem cardíaca: dose endovenosa em adulto:",
    ["0,5 mg", "1 mg", "5 mg", "10 mg"], 1,
    "1 mg EV a cada 3-5 minutos durante a RCP avançada do adulto."),
  q("enf12", "Emergências", "A posição lateral de segurança é indicada em vítima:",
    ["Em paragem cardíaca", "Inconsciente que respira", "Com hemorragia maciça", "Com fractura cervical"], 1,
    "Mantém via aérea pérvia e previne aspiração em inconscientes que respiram."),
  q("enf13", "Fundamentos de Enfermagem", "Pressão arterial considerada normal em adulto:",
    ["<120/80 mmHg", "140/90 mmHg", "150/100 mmHg", "<90/60 mmHg"], 0,
    "TA ideal <120/80; 120-129/<80 normal-elevada; ≥140/90 hipertensão (OMS)."),
  q("enf14", "Saúde Pública", "O PAV em Angola administra a vacina contra a poliomielite por via:",
    ["Subcutânea", "Intramuscular", "Oral e injectável", "Intradérmica"], 2,
    "PAV usa a VOP (oral) e a VIP (injectável) em esquema combinado."),
  q("enf15", "Saúde Materno-Infantil", "O sulfato de magnésio é usado em obstetrícia para:",
    ["Indução do parto", "Pré-eclâmpsia/eclâmpsia", "Hemorragia pós-parto", "Diabetes gestacional"], 1,
    "É a 1.ª escolha na prevenção e tratamento das convulsões da pré-eclâmpsia/eclâmpsia."),
  q("enf16", "Fundamentos de Enfermagem", "Equipamento de protecção individual mínimo para precauções padrão:",
    ["Apenas máscara", "Luvas, máscara, avental, óculos", "Apenas luvas", "Bata estéril"], 1,
    "Precauções padrão exigem barreira completa quando há risco de exposição a fluidos."),
  q("enf17", "Saúde Pública", "A taxa de mortalidade materna mede:",
    ["Mortes maternas/100.000 nados-vivos", "Mortes/1.000 grávidas", "Mortes durante parto/total partos", "Mortes pós-parto/total mulheres"], 0,
    "Indicador clássico expresso por 100.000 nados-vivos num determinado período."),
  q("enf18", "Farmacologia", "Antídoto da intoxicação por opiáceos:",
    ["Flumazenil", "Naloxona", "Atropina", "N-acetilcisteína"], 1,
    "Naloxona é antagonista dos receptores opióides; flumazenil é para benzodiazepinas."),
  q("enf19", "Emergências", "Triagem de Manchester: cor vermelha indica:",
    ["Não urgente", "Pouco urgente", "Urgente", "Emergente / atendimento imediato"], 3,
    "Vermelho = emergência, atendimento imediato; amarelo = urgente; verde = pouco urgente."),
  q("enf20", "Saúde Materno-Infantil", "Hemorragia pós-parto: causa mais frequente:",
    ["Lacerações", "Atonia uterina", "Retenção placentária", "Coagulopatia"], 1,
    "Atonia uterina é responsável por ~70% das HPP. Mnemónica: 4 T (Tono, Trauma, Tecido, Trombina)."),
  q("enf21", "Fundamentos de Enfermagem", "A escala de Glasgow varia de:",
    ["1 a 10", "3 a 15", "0 a 20", "5 a 25"], 1,
    "Pontuação total entre 3 (coma profundo) e 15 (consciente)."),
  q("enf22", "Saúde Pública", "O HIV é transmitido por todas as vias EXCEPTO:",
    ["Sexual", "Sanguínea", "Vertical", "Saliva em contacto social"], 3,
    "Não há transmissão por saliva, suor, lágrimas ou contacto social."),
  q("enf23", "Farmacologia", "Insulina rápida tem início de acção em aproximadamente:",
    ["5-15 minutos", "1-2 horas", "4-6 horas", "8-12 horas"], 0,
    "Insulinas regulares iniciam em 30 min; análogas rápidas (lispro/aspart) em 5-15 min."),
  q("enf24", "Emergências", "Choque hipovolémico: prioridade inicial é:",
    ["Antibiótico", "Reposição volémica com cristalóides", "Analgesia", "Vasopressor"], 1,
    "Reposição volémica precoce com cristalóides isotónicos (SF 0,9% ou Ringer)."),
  q("enf25", "Saúde Materno-Infantil", "Vacina BCG é administrada por via:",
    ["Subcutânea", "Intradérmica", "Intramuscular", "Oral"], 1,
    "BCG é aplicada por via intradérmica no músculo deltóide direito."),
  q("enf26", "Fundamentos de Enfermagem", "Úlceras por pressão grau II caracterizam-se por:",
    ["Eritema não branqueável", "Perda parcial da pele com flictena", "Perda total da pele expondo tecido subcutâneo", "Lesão profunda com osso visível"], 1,
    "Grau II: perda parcial da derme; flictena ou abrasão. Grau IV é o mais profundo."),
  q("enf27", "Saúde Pública", "O calendário PAV de Angola inclui aos 9 meses:",
    ["BCG", "Sarampo + Febre Amarela", "DTP", "Rotavírus"], 1,
    "Aos 9 meses: vacina contra o sarampo e febre amarela."),
  q("enf28", "Farmacologia", "Paracetamol em adulto: dose máxima diária habitual:",
    ["1 g", "2 g", "4 g", "8 g"], 2,
    "Dose máxima 4 g/dia; reduzir em hepatopatas e idosos."),
  q("enf29", "Emergências", "Manobra de Heimlich é indicada em:",
    ["AVC", "Obstrução das vias aéreas por corpo estranho", "Crise convulsiva", "Edema agudo do pulmão"], 1,
    "É manobra de desobstrução das vias aéreas em vítima consciente engasgada."),
  q("enf30", "Saúde Materno-Infantil", "Idade gestacional considerada termo:",
    ["≥34 semanas", "≥37 semanas", "≥40 semanas", "≥42 semanas"], 1,
    "Termo: 37 a 41 semanas e 6 dias. Pré-termo <37; pós-termo ≥42."),
  q("enf31", "Fundamentos de Enfermagem", "O processo de enfermagem inclui as fases:",
    ["Avaliação, planeamento, execução", "Investigação, diagnóstico, prescrição", "Colheita, diagnóstico, planeamento, execução, avaliação", "Triagem, tratamento, alta"], 2,
    "Modelo de 5 fases: colheita de dados, diagnóstico, planeamento, execução e avaliação."),
  q("enf32", "Saúde Pública", "A tuberculose pulmonar é diagnosticada laboratorialmente por:",
    ["Hemograma", "Baciloscopia / Xpert MTB/RIF", "Glicemia", "Urocultura"], 1,
    "Baciloscopia da expectoração e GeneXpert são os exames de eleição."),
  q("enf33", "Farmacologia", "Captopril pertence à classe dos:",
    ["Bloqueadores beta", "IECA", "Diuréticos", "Antagonistas do cálcio"], 1,
    "Inibidor da enzima de conversão da angiotensina (IECA), usado em HTA e ICC."),
  q("enf34", "Emergências", "Em queimaduras, a regra dos 9 estima:",
    ["Profundidade", "Superfície corporal queimada", "Necessidade de oxigénio", "Risco de infecção"], 1,
    "A regra de Wallace estima a percentagem de superfície corporal queimada."),
  q("enf35", "Saúde Materno-Infantil", "Profilaxia ocular do recém-nascido com:",
    ["Soro fisiológico", "Nitrato de prata 1% ou tetraciclina", "Penicilina", "Iodopovidona"], 1,
    "Credé: prevenção da oftalmia neonatal por gonococo nas primeiras horas de vida."),
  q("enf36", "Fundamentos de Enfermagem", "Soluções para hidratação parenteral isotónica incluem:",
    ["Glicose 50%", "SF 0,9%", "NaCl 3%", "Manitol 20%"], 1,
    "SF 0,9% e Ringer Lactato são isotónicos; glicose 50% é hipertónica."),
  q("enf37", "Saúde Pública", "A profilaxia da malária na grávida em Angola é feita com:",
    ["Cloroquina semanal", "Sulfadoxina-pirimetamina (TPI)", "Mefloquina diária", "Doxiciclina"], 1,
    "TPI com SP, dose única em cada consulta pré-natal a partir do 2.º trimestre."),
  q("enf38", "Farmacologia", "Furosemida é um diurético:",
    ["Tiazídico", "Da ansa de Henle", "Poupador de potássio", "Osmótico"], 1,
    "Actua no ramo ascendente espesso da ansa de Henle, inibindo o co-transportador Na/K/2Cl."),
  q("enf39", "Emergências", "AVC isquémico: janela terapêutica para trombólise:",
    ["1,5 horas", "3-4,5 horas", "12 horas", "24 horas"], 1,
    "Activador do plasminogénio tecidular (rt-PA) até 4,5 horas do início dos sintomas."),
  q("enf40", "Saúde Materno-Infantil", "Vacina DTP-HepB-Hib (pentavalente) é dada aos:",
    ["Nascimento", "2, 4 e 6 meses", "9 meses", "12 meses"], 1,
    "Esquema do PAV: 3 doses aos 2, 4 e 6 meses."),
  q("enf41", "Fundamentos de Enfermagem", "Cateterismo vesical de demora exige cuidado prioritário com:",
    ["Pressão arterial", "Higiene perineal e sistema fechado", "Glicemia capilar", "Posicionamento prono"], 1,
    "Para prevenir ITU associada ao cateter: técnica asséptica e sistema de drenagem fechado."),
  q("enf42", "Saúde Pública", "Indicador que mede saúde infantil:",
    ["Taxa bruta de mortalidade", "Mortalidade infantil <1 ano", "Esperança de vida", "Razão de masculinidade"], 1,
    "Mortalidade infantil = óbitos <1 ano por 1000 nados-vivos; espelha condições sociais e sanitárias."),
  q("enf43", "Farmacologia", "Diazepam é indicado em:",
    ["Hipertensão", "Convulsões e ansiedade", "Anti-emético", "Antipirético"], 1,
    "Benzodiazepina, anticonvulsivante, ansiolítico e relaxante muscular."),
  q("enf44", "Emergências", "ABCDE no atendimento ao trauma significa:",
    ["Avaliar, Bandagem, Curativo, Drenagem, Extracção", "Airway, Breathing, Circulation, Disability, Exposure", "Anamnese, Boca, Coluna, Dor, Exame", "Acordar, Banho, Comer, Dormir, Eliminar"], 1,
    "Sequência ATLS: via aérea, ventilação, circulação, disfunção neurológica, exposição."),
  q("enf45", "Saúde Materno-Infantil", "Período puerperal estende-se até:",
    ["1 semana", "2 semanas", "6-8 semanas pós-parto", "6 meses"], 2,
    "Puerpério tardio termina cerca de 6-8 semanas pós-parto, com involução uterina completa."),
  q("enf46", "Fundamentos de Enfermagem", "Controlo de infecção: as luvas devem ser trocadas:",
    ["Apenas no fim do turno", "Entre cada paciente e procedimento", "Apenas se sujas", "1 vez por hora"], 1,
    "Trocar entre pacientes e entre procedimentos no mesmo paciente."),
  q("enf47", "Saúde Pública", "Cólera tem como agente etiológico:",
    ["Salmonella typhi", "Vibrio cholerae", "Shigella", "E. coli"], 1,
    "Vibrio cholerae causa diarreia aquosa abundante; tratamento: reidratação rápida."),
  q("enf48", "Farmacologia", "Sulfato ferroso é usado em:",
    ["Anemia ferropriva", "Hipertensão", "Diabetes", "Hipotiroidismo"], 0,
    "Reposição oral de ferro elementar; melhor absorção em jejum, com vitamina C."),
  q("enf49", "Emergências", "Sinal de Babinski positivo sugere lesão:",
    ["Periférica", "Do neurónio motor superior", "Muscular", "Vascular"], 1,
    "Extensão do hálux após estímulo plantar indica lesão da via piramidal (NMS)."),
  q("enf50", "Ética", "Princípios bioéticos clássicos (Beauchamp e Childress):",
    ["Justiça, beneficência, autonomia, não-maleficência", "Respeito, hierarquia, ordem, fé", "Equidade, igualdade, dignidade, lealdade", "Caridade, fé, esperança, amor"], 0,
    "Os 4 princípios: autonomia, beneficência, não-maleficência e justiça."),
];

// =========================================================
// TÉCNICO DE ENFERMAGEM – 50 questões
// =========================================================
export const bancoTecEnfermagem: Question[] = [
  q("te1", "Procedimentos", "Ângulo de aplicação para injecção intramuscular:",
    ["15°", "45°", "60°", "90°"], 3,
    "IM aplica-se a 90° para garantir penetração no músculo."),
  q("te2", "Farmacologia", "Via mais rápida para adrenalina em choque anafiláctico:",
    ["Oral", "Subcutânea", "Intramuscular", "Tópica"], 2,
    "IM (face anterolateral da coxa) é recomendada por absorção rápida e segurança."),
  q("te3", "Saúde Pública", "BCG previne formas graves de:",
    ["Hepatite", "Tuberculose", "Sarampo", "Poliomielite"], 1,
    "Protege contra meningite tuberculosa e tuberculose miliar."),
  q("te4", "Procedimentos", "Ângulo da injecção subcutânea:",
    ["15°", "45°", "60°", "90°"], 1,
    "SC: 45° (90° em obesos com agulha curta)."),
  q("te5", "Procedimentos", "Locais de aplicação IM em adulto:",
    ["Ventroglútea, vasto lateral, deltóide", "Apenas glútea", "Apenas deltóide", "Abdómen"], 0,
    "Ventroglútea é a mais segura; vasto lateral e deltóide também são usados."),
  q("te6", "Farmacologia", "Insulina é administrada habitualmente por via:",
    ["Endovenosa", "Subcutânea", "Intramuscular", "Oral"], 1,
    "Insulina destina-se a via SC; só em emergência (cetoacidose) é EV em bomba."),
  q("te7", "Procedimentos", "Tipo de agulha para colheita de sangue venoso:",
    ["13×4,5", "25×7", "30×7 ou 25×8 (sistema vácuo)", "40×12"], 2,
    "Calibre 21G (25×8) ou 22G é o mais usado para venopunção."),
  q("te8", "Saúde Pública", "Cadeia de frio das vacinas: temperatura ideal:",
    ["-20 °C a 0 °C", "+2 °C a +8 °C", "+10 °C a +15 °C", "Ambiente"], 1,
    "Conservação no frigorífico entre +2 e +8 °C."),
  q("te9", "Procedimentos", "Sinal vital que avalia oxigenação:",
    ["TA", "SatO2", "Temperatura", "FC"], 1,
    "Saturação periférica de oxigénio reflecte oxigenação do sangue arterial."),
  q("te10", "Emergências", "Pressão arterial considerada hipotensão em adulto:",
    ["<120/80", "<90/60", "<140/90", "<100/70"], 1,
    "Hipotensão clínica: TA sistólica <90 e diastólica <60."),
  q("te11", "Procedimentos", "Antes de qualquer procedimento, o técnico deve:",
    ["Lavar as mãos", "Calçar luvas estéreis", "Pedir TA", "Aspirar a seringa"], 0,
    "Higiene das mãos é a medida mais efectiva de prevenção de infecções."),
  q("te12", "Farmacologia", "Diluição habitual da dipirona EV em adulto:",
    ["Pura, em bólus rápido", "Diluída em SF, infusão lenta", "Em glicose 50%", "Sublingual"], 1,
    "Diluir e administrar lentamente para evitar hipotensão."),
  q("te13", "Procedimentos", "Curativo simples deve ser feito:",
    ["Sem luvas", "Com técnica asséptica", "Apenas com álcool", "Sem trocar"], 1,
    "Técnica asséptica reduz risco de infecção da ferida."),
  q("te14", "Saúde Pública", "Dengue: controlo principal é:",
    ["Antibiótico", "Vacina universal", "Eliminação de criadouros do Aedes", "Antiviral"], 2,
    "Não há tratamento específico; prevenção centra-se no controlo do vector."),
  q("te15", "Procedimentos", "Pulso radial é palpado:",
    ["Pescoço", "Punho, lateral ao tendão flexor", "Pé", "Inguinal"], 1,
    "Artéria radial palpa-se na face anterior do punho, lateral ao tendão do flexor radial."),
  q("te16", "Emergências", "Em paragem cardiorrespiratória, primeiro passo após chamar ajuda:",
    ["Ventilação", "Compressões torácicas", "Adrenalina", "Glicemia"], 1,
    "C-A-B: iniciar imediatamente compressões torácicas de alta qualidade."),
  q("te17", "Procedimentos", "Higiene oral em paciente acamado: frequência mínima:",
    ["1×/dia", "2×/dia", "3×/dia", "Apenas semanal"], 2,
    "Pelo menos 3 vezes ao dia, ou após cada refeição, para prevenir pneumonia aspirativa."),
  q("te18", "Farmacologia", "Conservação da insulina aberta em uso:",
    ["Frigorífico, sempre", "Temperatura ambiente até 28 dias", "Congelador", "Banho-maria"], 1,
    "Frasco em uso pode ficar à temperatura ambiente (≤25 °C) até 4 semanas."),
  q("te19", "Procedimentos", "Mudança de decúbito em acamados deve ser feita a cada:",
    ["12 horas", "6 horas", "2-3 horas", "Apenas à noite"], 2,
    "Cada 2-3 horas para prevenir úlceras por pressão."),
  q("te20", "Saúde Pública", "PAV: vacina dada ao nascimento:",
    ["BCG e VOP", "Pentavalente", "Sarampo", "Febre amarela"], 0,
    "À nascença: BCG (intradérmica) e VOP zero (oral)."),
  q("te21", "Procedimentos", "Material para venopunção inclui:",
    ["Garrote, álcool, agulha, algodão", "Luvas estéreis e bata", "Apenas seringa", "Soro fisiológico apenas"], 0,
    "Material básico: garrote, antisséptico, agulha/scalp, seringa, algodão e adesivo."),
  q("te22", "Emergências", "Glicemia capilar para hipoglicémia em adulto consciente: dar:",
    ["Insulina rápida", "Glicose oral 15-20 g", "Soro hipotónico", "Aguardar"], 1,
    "Regra dos 15: 15 g de glicose oral e reavaliar em 15 minutos."),
  q("te23", "Procedimentos", "Termómetro digital axilar deve permanecer:",
    ["10 segundos", "Até apito (3-5 min)", "30 minutos", "1 hora"], 1,
    "Manter até sinal sonoro; valores normais axilares 36-37 °C."),
  q("te24", "Saúde Pública", "Doença de notificação obrigatória em Angola:",
    ["Gripe comum", "Cólera", "Cefaleia", "Lombalgia"], 1,
    "Cólera, sarampo, febre amarela, poliomielite, raiva, tuberculose, malária, COVID-19 etc."),
  q("te25", "Procedimentos", "Aspiração de secreções: pressão de aspiração em adulto:",
    ["50-80 mmHg", "100-150 mmHg", "200-300 mmHg", ">350 mmHg"], 1,
    "Pressões elevadas lesam a mucosa; manter 100-150 mmHg em adulto."),
  q("te26", "Farmacologia", "Antitérmico de 1.ª linha em pediatria:",
    ["Ácido acetilsalicílico", "Paracetamol", "Diclofenac", "Cetoprofeno"], 1,
    "AAS evita-se em crianças por risco de Síndrome de Reye."),
  q("te27", "Procedimentos", "Soro de reidratação oral é indicado em:",
    ["Vómitos incoercíveis", "Diarreia aguda sem desidratação grave", "Choque", "Coma"], 1,
    "1.ª linha em desidratação leve a moderada por diarreia aguda."),
  q("te28", "Emergências", "Convulsão tónico-clónica: prioridade é:",
    ["Conter o paciente", "Proteger a cabeça e via aérea", "Colocar objecto na boca", "Dar água"], 1,
    "Proteger contra trauma; nunca introduzir objectos na boca."),
  q("te29", "Procedimentos", "Frequência respiratória normal em adulto:",
    ["6-10 cpm", "12-20 cpm", "25-30 cpm", "30-40 cpm"], 1,
    "Eupneia: 12-20 ciclos por minuto."),
  q("te30", "Saúde Pública", "Profilaxia pós-exposição ao HIV deve ser iniciada idealmente em até:",
    ["2 horas", "72 horas", "1 semana", "1 mês"], 1,
    "Quanto mais precoce melhor; idealmente nas primeiras 2 horas, máximo 72 horas."),
  q("te31", "Procedimentos", "Algaliação: lubrificação da sonda em mulher faz-se com:",
    ["Álcool", "Lubrificante hidrossolúvel", "Vaselina", "Iodopovidona"], 1,
    "Gel hidrossolúvel evita lesão e infecção; nunca vaselina."),
  q("te32", "Farmacologia", "Soro glicosado a 5% é considerado:",
    ["Isotónico (clinicamente)", "Hipertónico", "Hipotónico após metabolização", "Soro coloide"], 2,
    "Inicialmente isotónico; após metabolização da glicose comporta-se como hipotónico."),
  q("te33", "Procedimentos", "Frequência cardíaca normal em adulto em repouso:",
    ["40-50 bpm", "60-100 bpm", "100-130 bpm", ">140 bpm"], 1,
    "Eufrequência: 60-100 bpm. Bradicardia <60; taquicardia >100."),
  q("te34", "Emergências", "Vítima inconsciente que respira: posicionar em:",
    ["Decúbito dorsal", "Lateral de segurança", "Trendelenburg", "Sentado"], 1,
    "PLS protege via aérea e previne aspiração."),
  q("te35", "Procedimentos", "Banho no leito tem como objectivo principal:",
    ["Diagnóstico", "Higiene, conforto e avaliação da pele", "Prescrição", "Punção"], 1,
    "Promove higiene e oportunidade para inspecção da pele e mobilização."),
  q("te36", "Saúde Pública", "PAV calendário aos 2 meses:",
    ["BCG", "Pentavalente, VOP, Pneumo, Rotavírus", "Sarampo", "Febre amarela"], 1,
    "Aos 2 meses iniciam-se as vacinas pentavalente, VOP, pneumocócica e rotavírus."),
  q("te37", "Procedimentos", "Sondagem nasogástrica: posição do paciente:",
    ["Decúbito ventral", "Fowler / semi-sentado", "Trendelenburg", "Lateral esquerdo"], 1,
    "Cabeça elevada (45°) facilita progressão e reduz risco de aspiração."),
  q("te38", "Farmacologia", "Antibiótico de 1.ª linha para infecção urinária não complicada:",
    ["Penicilina", "Cotrimoxazol/nitrofurantoína", "Vancomicina", "Cefepima"], 1,
    "Esquemas curtos com SMX-TMP, nitrofurantoína ou fosfomicina."),
  q("te39", "Procedimentos", "Soro fisiológico 0,9% contém NaCl a:",
    ["0,45%", "0,9%", "3%", "5%"], 1,
    "0,9% (9 g de NaCl por litro), isotónico em relação ao plasma."),
  q("te40", "Emergências", "Hemorragia externa: 1.ª medida:",
    ["Torniquete imediato", "Compressão directa", "Levantar o paciente", "Aspirar a ferida"], 1,
    "Compressão directa local é a 1.ª medida; torniquete só em hemorragias maciças não controláveis."),
  q("te41", "Procedimentos", "Antes de administrar transfusão verifica-se:",
    ["Apenas o nome", "Identificação completa, grupo ABO/Rh, prova cruzada", "Glicemia", "Apenas o número da bolsa"], 1,
    "Dupla checagem com identificação, ABO/Rh e prova cruzada é obrigatória."),
  q("te42", "Saúde Pública", "Reservatório principal da malária:",
    ["Anopheles fêmea", "Homem", "Bovinos", "Roedores"], 1,
    "O homem é o reservatório principal; o Anopheles é o vector."),
  q("te43", "Procedimentos", "Oxigenoterapia por óculos nasais: fluxo máximo recomendado:",
    ["1 L/min", "5-6 L/min", "15 L/min", "30 L/min"], 1,
    "Acima de 6 L/min causa secura/desconforto; usar máscara para fluxos maiores."),
  q("te44", "Farmacologia", "Heparina não fraccionada antagoniza-se com:",
    ["Vitamina K", "Sulfato de protamina", "Naloxona", "Atropina"], 1,
    "Protamina neutraliza a heparina; vitamina K é antídoto da varfarina."),
  q("te45", "Procedimentos", "Resíduos perfurocortantes descartam-se em:",
    ["Saco preto", "Caixa rígida amarela (Grupo E)", "Saco branco leitoso", "Lixo comum"], 1,
    "Recipientes rígidos próprios identificados como resíduos do grupo E."),
  q("te46", "Emergências", "Sinal precoce de choque:",
    ["Hipertensão", "Taquicardia e pele fria", "Bradicardia", "Hipertermia"], 1,
    "Resposta simpática: taquicardia, vasoconstrição periférica e palidez."),
  q("te47", "Procedimentos", "Glicemia capilar normal em jejum:",
    ["<70 mg/dL", "70-99 mg/dL", "100-125 mg/dL", "≥126 mg/dL"], 1,
    "Normal: 70-99 mg/dL. 100-125 pré-diabetes; ≥126 confirmar diabetes."),
  q("te48", "Saúde Pública", "Hanseníase é causada por:",
    ["Mycobacterium tuberculosis", "Mycobacterium leprae", "Treponema pallidum", "HIV"], 1,
    "Mycobacterium leprae (bacilo de Hansen); doença de notificação obrigatória."),
  q("te49", "Procedimentos", "Compressas estéreis devem ser manipuladas com:",
    ["Mãos limpas", "Pinça estéril", "Qualquer luva", "Toalha de papel"], 1,
    "Manuseio com pinça ou luva estéril mantém esterilidade do material."),
  q("te50", "Ética", "Confidencialidade dos dados do paciente é dever:",
    ["Apenas do médico", "De toda a equipa de saúde", "Apenas administrativos", "Opcional"], 1,
    "Sigilo abrange toda a equipa que tem acesso à informação clínica."),
];

// =========================================================
// FARMACÊUTICO – 50 questões
// =========================================================
export const bancoFarmaceutico: Question[] = [
  q("f1", "Farmacologia", "Classe farmacológica do Omeprazol:",
    ["Antagonista H2", "Inibidor da bomba de protões", "Antiácido", "Procinético"], 1,
    "IBP que reduz secreção ácida ao inibir a H+/K+ ATPase nas células parietais."),
  q("f2", "Legislação", "Em Angola, regulação de medicamentos compete a:",
    ["INSP", "ARMED", "Direcção Nacional de Medicamentos", "OMS"], 1,
    "ARMED – Agência Reguladora de Medicamentos é a autoridade reguladora nacional."),
  q("f3", "Farmácia Hospitalar", "Cadeia de frio do PAV: temperatura:",
    ["-20 °C a 0 °C", "+2 °C a +8 °C", "+8 °C a +15 °C", "Ambiente"], 1,
    "Conservação refrigerada entre +2 e +8 °C."),
  q("f4", "Farmacotécnica", "Forma farmacêutica sólida de uso oral:",
    ["Xarope", "Comprimido", "Pomada", "Solução"], 1,
    "Comprimidos, cápsulas, pílulas e granulados são formas sólidas orais."),
  q("f5", "Farmacotécnica", "Constituintes essenciais de uma fórmula:",
    ["Princípio activo e excipientes", "Apenas princípio activo", "Apenas conservantes", "Apenas corantes"], 0,
    "Toda fórmula contém princípio activo e excipientes (veículos, conservantes, etc.)."),
  q("f6", "Vias de Administração", "Via parenteral é:",
    ["Oral", "Sublingual", "Endovenosa", "Rectal"], 2,
    "Parenteral = injectável (EV, IM, SC, ID); oral, rectal e sublingual são enterais."),
  q("f7", "Farmacocinética", "ADME corresponde a:",
    ["Absorção, Distribuição, Metabolização, Excreção", "Acção, Dose, Meia-vida, Efeito", "Antibiótico, Diluente, Mistura, Excipiente", "Análise, Dosagem, Mistura, Embalagem"], 0,
    "Etapas farmacocinéticas: absorção, distribuição, biotransformação e excreção."),
  q("f8", "Farmacodinâmica", "Relação dose-efeito é estudo da:",
    ["Farmacocinética", "Farmacodinâmica", "Toxicologia exclusivamente", "Galénica"], 1,
    "Farmacodinâmica avalia a relação entre concentração e efeito biológico."),
  q("f9", "Farmacologia", "AINE com efeito antiplaquetário irreversível:",
    ["Paracetamol", "Ácido acetilsalicílico", "Ibuprofeno", "Diclofenac"], 1,
    "AAS acetila irreversivelmente a COX-1 plaquetária por toda a vida da plaqueta."),
  q("f10", "Farmácia Hospitalar", "Boas práticas de armazenamento exigem temperatura ambiente entre:",
    ["0-10 °C", "15-25 °C", "30-40 °C", ">40 °C"], 1,
    "OMS define temperatura ambiente controlada entre 15 e 25 °C, humidade <60%."),
  q("f11", "Legislação", "Receita de psicotrópicos em Angola requer:",
    ["Receita simples", "Receita especial controlada", "Verbal", "Sem receita"], 1,
    "Substâncias controladas exigem receita especial em duplicado, com retenção."),
  q("f12", "Farmácia Hospitalar", "Sistema de distribuição de medicamentos por dose unitária garante:",
    ["Maior risco de erro", "Maior segurança e rastreabilidade", "Menor custo absoluto", "Distribuição mensal"], 1,
    "Reduz erros, desperdício e melhora rastreabilidade comparado a stock por enfermaria."),
  q("f13", "Farmacotécnica", "Suspensões farmacêuticas devem ser:",
    ["Filtradas antes de uso", "Agitadas antes de uso", "Aquecidas", "Diluídas em álcool"], 1,
    "São sistemas heterogéneos que precisam de homogeneização antes da dose."),
  q("f14", "Farmacocinética", "Biotransformação ocorre principalmente em:",
    ["Rim", "Fígado", "Pulmão", "Pele"], 1,
    "O fígado é o principal órgão de biotransformação (citocromo P450)."),
  q("f15", "Farmacologia", "Antagonista das benzodiazepinas:",
    ["Naloxona", "Flumazenil", "N-acetilcisteína", "Atropina"], 1,
    "Flumazenil reverte sedação e depressão respiratória por benzodiazepinas."),
  q("f16", "Farmacologia", "Amoxicilina pertence à classe dos:",
    ["Macrólidos", "Beta-lactâmicos (penicilinas)", "Quinolonas", "Aminoglicosídeos"], 1,
    "Aminopenicilina; actua na parede bacteriana inibindo PBPs."),
  q("f17", "Farmácia Hospitalar", "Inventário rotativo caracteriza-se por:",
    ["Contagem total anual", "Contagens parciais e contínuas ao longo do ano", "Sem registos", "Apenas ao fim do ano"], 1,
    "Permite controlo permanente e detecção precoce de divergências de stock."),
  q("f18", "Farmacotécnica", "Diluir 100 mL de solução a 20% para 500 mL produz concentração final de:",
    ["2%", "4%", "10%", "20%"], 1,
    "C1V1 = C2V2 → 20×100 = C2×500 → C2 = 4%."),
  q("f19", "Vias de Administração", "Via sublingual evita o efeito de 1.ª passagem porque:",
    ["É rectal", "Drena para circulação sistémica directamente", "Passa pelo fígado primeiro", "É absorvida no estômago"], 1,
    "Drenagem venosa sublingual vai à veia cava, evitando metabolismo hepático inicial."),
  q("f20", "Legislação", "Prazo de validade refere-se a:",
    ["Tempo até abertura", "Período em que o medicamento mantém qualidade nas condições especificadas", "Tempo após fabricação até venda", "Tempo de transporte"], 1,
    "Garante eficácia e segurança quando armazenado conforme indicado pelo fabricante."),
  q("f21", "Farmácia Hospitalar", "Medicamentos termolábeis requerem:",
    ["Armazenamento ambiente", "Conservação no frigorífico (2-8 °C)", "Congelação", "Local quente"], 1,
    "Vacinas, insulinas e biológicos exigem cadeia de frio rigorosa."),
  q("f22", "Farmacologia", "Mecanismo do paracetamol:",
    ["Inibição COX-1 periférica forte", "Inibição central de COX, com pouca acção anti-inflamatória", "Bloqueio H2", "IECA"], 1,
    "Acção predominantemente central, analgésico e antipirético com baixa acção anti-inflamatória."),
  q("f23", "Farmacocinética", "Meia-vida (t½) é tempo para:",
    ["Concentração cair a 0", "Concentração cair a metade", "Eliminação total", "Atingir pico plasmático"], 1,
    "Tempo necessário para a concentração plasmática se reduzir a 50%."),
  q("f24", "Legislação", "Genérico difere do medicamento de referência por:",
    ["Possuir mesmo princípio activo, dose e bioequivalência", "Diferente princípio activo", "Diferente dosagem obrigatoriamente", "Diferente indicação"], 0,
    "Genérico tem mesma substância, dose, forma e bioequivalência ao referência."),
  q("f25", "Farmacologia", "Antídoto da intoxicação por paracetamol:",
    ["Naloxona", "N-acetilcisteína", "Atropina", "Flumazenil"], 1,
    "NAC repõe glutationa hepática; idealmente nas primeiras 8-10 horas."),
  q("f26", "Farmácia Hospitalar", "PEPS (FEFO) significa:",
    ["Primeiro a entrar, primeiro a sair (validade)", "Primeiro a expirar, primeiro a sair", "Primeiro empacotado", "Sem ordem"], 1,
    "FEFO – First Expire, First Out: prioriza saída do que vence primeiro."),
  q("f27", "Farmacotécnica", "Excipiente tem por função:",
    ["Substituir o princípio activo", "Veicular, estabilizar e modular libertação", "Aumentar toxicidade", "Servir como contaminante"], 1,
    "Componente inactivo essencial para forma farmacêutica e biodisponibilidade."),
  q("f28", "Farmacologia", "Anti-hipertensor que pode causar tosse seca:",
    ["Atenolol", "Captopril (IECA)", "Hidroclorotiazida", "Amlodipina"], 1,
    "IECA aumentam bradicinina, causando tosse seca em ~10% dos doentes."),
  q("f29", "Vias de Administração", "Via que apresenta maior biodisponibilidade:",
    ["Oral", "Endovenosa", "Subcutânea", "Tópica"], 1,
    "EV tem 100% de biodisponibilidade por entrar directamente na circulação."),
  q("f30", "Farmácia Hospitalar", "Reacção adversa medicamentosa (RAM) deve ser:",
    ["Ignorada", "Notificada à autoridade (farmacovigilância)", "Discutida só verbalmente", "Apenas registada no prontuário"], 1,
    "Notificação à ARMED via sistema de farmacovigilância nacional."),
  q("f31", "Legislação", "Substâncias de Tabela 1 (Convenção 1961):",
    ["Antibióticos", "Estupefacientes (ex.: morfina, heroína)", "Paracetamol", "Vitaminas"], 1,
    "Inclui opióides como morfina; heroína está em tabela mais restrita."),
  q("f32", "Farmacologia", "Antibiótico contra-indicado em grávidas e crianças <8 anos:",
    ["Amoxicilina", "Tetraciclinas", "Azitromicina", "Cefalexina"], 1,
    "Tetraciclinas depositam-se em ossos e dentes em desenvolvimento."),
  q("f33", "Farmacocinética", "Volume de distribuição (Vd) elevado indica:",
    ["Confinamento ao plasma", "Boa distribuição tecidular", "Falta de absorção", "Excreção rápida"], 1,
    "Vd alto = fármaco lipofílico, distribui-se amplamente nos tecidos."),
  q("f34", "Farmácia Hospitalar", "Mistura intravenosa de antibióticos deve ser feita preferencialmente em:",
    ["Bancada da enfermaria", "Câmara de fluxo laminar", "Sala de espera", "Cozinha"], 1,
    "Manipulação asséptica em CFL evita contaminação."),
  q("f35", "Farmacotécnica", "Forma farmacêutica para libertação prolongada permite:",
    ["Doses mais frequentes", "Manter níveis terapêuticos com menos doses", "Início mais rápido", "Maior pico plasmático"], 1,
    "Reduz oscilações e melhora adesão (1-2 doses/dia)."),
  q("f36", "Farmacologia", "Varfarina antagoniza-se com:",
    ["Sulfato de protamina", "Vitamina K", "Naloxona", "Atropina"], 1,
    "Vitamina K reverte o efeito da varfarina; protamina é para heparina."),
  q("f37", "Vias de Administração", "Via rectal é útil quando:",
    ["Paciente vomita ou inconsciente", "Desejado efeito imediato endovenoso", "Apenas para anestesia geral", "Apenas crianças"], 0,
    "Indicada quando via oral não é possível; absorção variável evitando 1.ª passagem parcial."),
  q("f38", "Farmácia Hospitalar", "Comissão de Farmácia e Terapêutica tem por função:",
    ["Fixar preços de venda externa", "Selecção e uso racional de medicamentos no hospital", "Auditoria fiscal", "Limpeza"], 1,
    "Define lista padronizada e protocolos terapêuticos institucionais."),
  q("f39", "Legislação", "Receita médica simples é válida geralmente por:",
    ["7 dias", "30 dias", "6 meses", "Ilimitada"], 1,
    "Validade habitual é de 30 dias (varia para psicotrópicos)."),
  q("f40", "Farmacologia", "Diabetes tipo 2 – fármaco de 1.ª linha:",
    ["Insulina basal", "Metformina", "Glibenclamida", "Acarbose"], 1,
    "Metformina é a 1.ª escolha por reduzir resistência à insulina e mortalidade."),
  q("f41", "Farmácia Hospitalar", "Lavagem cirúrgica das mãos antes de manipulação estéril dura:",
    ["10 segundos", "20 segundos", "2-5 minutos", "30 minutos"], 2,
    "Antissepsia cirúrgica clássica entre 2 e 5 minutos."),
  q("f42", "Farmacotécnica", "Uma solução a 1:1000 corresponde a:",
    ["1 mg/mL", "10 mg/mL", "100 mg/mL", "0,1 mg/mL"], 0,
    "1 g em 1000 mL = 1 mg por mL (ex.: adrenalina 1:1000)."),
  q("f43", "Farmacologia", "Anticoagulante oral directo (DOAC):",
    ["Varfarina", "Heparina", "Rivaroxabana", "AAS"], 2,
    "Rivaroxabana, apixabana e edoxabana inibem o factor Xa; dabigatrana inibe trombina."),
  q("f44", "Vias de Administração", "Aerossol e nebulização são vias:",
    ["Tópicas dérmicas", "Inalatórias", "Endovenosas", "Sublinguais"], 1,
    "Permitem acção pulmonar rápida com baixa absorção sistémica."),
  q("f45", "Farmacocinética", "Excreção renal é favorecida em fármacos:",
    ["Lipossolúveis", "Hidrossolúveis", "Voláteis", "Apolares"], 1,
    "Compostos hidrossolúveis ou metabolizados em formas polares são eliminados pelo rim."),
  q("f46", "Farmácia Hospitalar", "Medicamento High-Alert (alta vigilância) inclui:",
    ["Paracetamol", "Insulina, heparina, opióides, KCl concentrado", "Soro fisiológico", "Vitaminas"], 1,
    "ISMP define: pequenos erros podem causar dano grave; exigem dupla checagem."),
  q("f47", "Farmacologia", "Antibiótico de eleição na sífilis:",
    ["Penicilina benzatínica", "Vancomicina", "Doxiciclina sempre", "Metronidazol"], 0,
    "Penicilina benzatínica IM é o tratamento de 1.ª escolha em todas as fases."),
  q("f48", "Legislação", "Farmacovigilância tem por objectivo:",
    ["Aumentar vendas", "Detectar, avaliar e prevenir RAM", "Fiscalizar preços", "Distribuir amostras"], 1,
    "OMS: ciência para detectar e prevenir reacções adversas e outros problemas com medicamentos."),
  q("f49", "Farmacotécnica", "Preparações tópicas semi-sólidas:",
    ["Comprimidos", "Pomadas, cremes, géis", "Xaropes", "Cápsulas"], 1,
    "Pomadas, cremes, pastas e géis são formas semi-sólidas para uso tópico."),
  q("f50", "Farmácia Hospitalar", "Conduta perante medicamento vencido:",
    ["Dispensar com aviso", "Segregar e descartar conforme PGRSS", "Devolver ao paciente", "Diluir e reusar"], 1,
    "Segregação imediata, registo e descarte conforme plano de gestão de resíduos."),
];
