import { Question } from "./concursos";

const q = (
  id: string, disciplina: string, enunciado: string,
  opcoes: string[], correta: number, comentario: string,
): Question => ({ id, disciplina, enunciado, opcoes, correta, comentario });

// +50 questões de Laboratório (Análises Clínicas - MINSA)
export const bancoLabExt2: Question[] = [
  q("lby1", "Hematologia", "Valor de referência de plaquetas (adulto):",
    ["50-100 mil/µL", "150-450 mil/µL", "500-700 mil/µL", "10-50 mil/µL"], 1,
    "Plaquetas normais: 150.000-450.000/µL."),
  q("lby2", "Hematologia", "Trombocitopenia define-se com plaquetas abaixo de:",
    ["300.000", "200.000", "150.000", "100.000"], 2,
    "Abaixo de 150.000/µL."),
  q("lby3", "Hematologia", "Leucocitose neutrofílica sugere:",
    ["Infecção viral", "Infecção bacteriana aguda", "Alergia", "Parasitose"], 1,
    "Neutrofilia é típica de infecção bacteriana."),
  q("lby4", "Hematologia", "Eosinofilia sugere:",
    ["Bacteriana", "Parasitose/alergia", "Tuberculose", "Hipotiroidismo"], 1,
    "Eosinófilos elevam em parasitoses e alergias."),
  q("lby5", "Hematologia", "VCM elevado (>100 fL) caracteriza anemia:",
    ["Microcítica", "Normocítica", "Macrocítica", "Falciforme"], 2,
    "Macrocítica (deficiência B12/folato)."),
  q("lby6", "Hematologia", "Reticulócitos elevados indicam:",
    ["Aplasia medular", "Resposta medular activa", "Hemólise crónica controlada", "Leucemia"], 1,
    "Indica resposta eritropoiética."),
  q("lby7", "Hematologia", "Velocidade de sedimentação (VS) eleva-se em:",
    ["Policitemia", "Inflamação/infecção", "Desidratação", "Anemia ferropriva apenas"], 1,
    "VS é marcador inespecífico de inflamação."),
  q("lby8", "Hematologia", "TTPa avalia via:",
    ["Extrínseca", "Intrínseca e comum", "Plaquetária", "Fibrinolítica"], 1,
    "TTPa: via intrínseca e comum."),
  q("lby9", "Hematologia", "TP avalia via:",
    ["Intrínseca", "Extrínseca e comum", "Plaquetária", "Fibrinolítica"], 1,
    "TP/INR: via extrínseca."),
  q("lby10", "Hematologia", "Tempo de sangria avalia:",
    ["Coagulação", "Função plaquetária e vascular", "Fibrinólise", "Hemoglobina"], 1,
    "Hemostase primária."),
  q("lby11", "Hematologia", "Esfregaço com hemácias em foice sugere:",
    ["Talassemia", "Anemia falciforme", "Esferocitose", "Anemia ferropriva"], 1,
    "Drepanócitos = HbS."),
  q("lby12", "Hematologia", "Esferocitose hereditária: teste útil:",
    ["Eletroforese de Hb", "Fragilidade osmótica", "TP/INR", "Coombs directo"], 1,
    "Curva de fragilidade osmótica aumentada."),
  q("lby13", "Microbiologia", "Bactéria Gram-negativa típica de ITU:",
    ["Staph. aureus", "Escherichia coli", "Strep. pyogenes", "Clostridium"], 1,
    "E. coli é a principal causa de ITU."),
  q("lby14", "Microbiologia", "Meio de Thayer-Martin é selectivo para:",
    ["E. coli", "Neisseria gonorrhoeae", "Salmonella", "Cândida"], 1,
    "Cultura de gonococo."),
  q("lby15", "Microbiologia", "Teste de catalase positivo distingue:",
    ["Staphylococcus de Streptococcus", "E. coli de Salmonella", "Gram+ de Gram-", "Aerobio de anaeróbio"], 0,
    "Staph é catalase+, Strep é catalase-."),
  q("lby16", "Microbiologia", "Teste da coagulase identifica:",
    ["S. epidermidis", "S. aureus", "S. saprophyticus", "Enterococcus"], 1,
    "S. aureus é coagulase positivo."),
  q("lby17", "Microbiologia", "Meio MacConkey selecciona:",
    ["Gram+ apenas", "Enterobactérias (Gram-)", "Anaeróbios", "Fungos"], 1,
    "Selectivo para Gram-negativos entéricos."),
  q("lby18", "Microbiologia", "Cultura de fezes para Salmonella - meio:",
    ["Sabouraud", "SS / Hektoen", "Löwenstein", "Chocolate"], 1,
    "SS ou Hektoen são meios selectivos."),
  q("lby19", "Microbiologia", "Coloração de Gram - descorante:",
    ["Água", "Álcool-acetona", "Lugol", "Fucsina"], 1,
    "Álcool-acetona descora os Gram-negativos."),
  q("lby20", "Microbiologia", "Identificação rápida de Streptococcus β-hemolítico do grupo A:",
    ["Coagulase", "Bacitracina sensível", "Optoquina sensível", "Catalase+"], 1,
    "S. pyogenes é sensível à bacitracina."),
  q("lby21", "Microbiologia", "Optoquina sensível identifica:",
    ["S. pneumoniae", "S. aureus", "E. coli", "Klebsiella"], 0,
    "Pneumococo é sensível à optoquina."),
  q("lby22", "Microbiologia", "Hemocultura: nº ideal de amostras antes de antibiótico:",
    ["1", "2-3 em locais distintos", "5", "Nenhuma"], 1,
    "Pelo menos 2-3 amostras de locais diferentes."),
  q("lby23", "Bioquímica", "Tubo de fluoreto de sódio preserva:",
    ["Hemograma", "Glicose (inibe glicólise)", "Coagulação", "VS"], 1,
    "Fluoreto inibe glicólise e estabiliza glicose."),
  q("lby24", "Bioquímica", "Bilirrubina indirecta aumenta em:",
    ["Obstrução biliar", "Hemólise", "Litíase coledociana", "Hepatite colestática"], 1,
    "Hemólise eleva bilirrubina não-conjugada."),
  q("lby25", "Bioquímica", "Bilirrubina directa aumentada sugere:",
    ["Hemólise", "Colestase / obstrução", "Anemia ferropriva", "Eritropoiese aumentada"], 1,
    "Colestase intra ou extra-hepática."),
  q("lby26", "Bioquímica", "Amilase e lipase elevadas indicam:",
    ["Hepatite", "Pancreatite aguda", "Cólera", "ITU"], 1,
    "Marcadores de pancreatite."),
  q("lby27", "Bioquímica", "CK-MB e troponina elevam-se em:",
    ["AVC", "Enfarte agudo do miocárdio", "Hepatite", "Insuficiência renal"], 1,
    "Marcadores de necrose miocárdica."),
  q("lby28", "Bioquímica", "Colesterol total desejável (adulto):",
    ["<200 mg/dL", "<240", "<300", "<400"], 0,
    "Desejável <200 mg/dL."),
  q("lby29", "Bioquímica", "HDL é considerado factor:",
    ["De risco", "Protector cardiovascular", "Neutro", "Inflamatório"], 1,
    "HDL transporta colesterol para o fígado."),
  q("lby30", "Bioquímica", "Hipocalemia define-se com K+:",
    ["<5,5", "<3,5 mEq/L", "<2,0", "<1,0"], 1,
    "Hipocalemia: K+ <3,5 mEq/L."),
  q("lby31", "Bioquímica", "Gasometria - pH normal:",
    ["6,8-7,0", "7,35-7,45", "7,5-7,8", "8,0-8,2"], 1,
    "pH arterial normal."),
  q("lby32", "Bioquímica", "Acidose metabólica caracteriza-se por:",
    ["pH alto, HCO3 alto", "pH baixo, HCO3 baixo", "pH baixo, PCO2 alto", "pH alto, PCO2 baixo"], 1,
    "Redução de bicarbonato e pH."),
  q("lby33", "Bioquímica", "Microalbuminúria é marcador precoce de:",
    ["Cirrose", "Nefropatia diabética", "ITU", "Anemia"], 1,
    "Lesão glomerular precoce no diabético."),
  q("lby34", "Bioquímica", "PSA é marcador de:",
    ["Próstata", "Mama", "Pulmão", "Ovário"], 0,
    "Antígeno prostático específico."),
  q("lby35", "Bioquímica", "CA-125 é marcador de:",
    ["Cólon", "Ovário", "Mama", "Próstata"], 1,
    "Marcador tumoral de ovário."),
  q("lby36", "Imunohematologia", "Receptor universal de hemácias:",
    ["O-", "A+", "AB+", "B-"], 2,
    "AB+ é receptor universal."),
  q("lby37", "Imunohematologia", "Teste de Coombs directo detecta:",
    ["Antígenos eritrocitários", "Anticorpos ligados às hemácias do paciente", "Plaquetas", "Leucócitos"], 1,
    "Coombs directo: anticorpos já fixados às hemácias."),
  q("lby38", "Imunohematologia", "Coombs indirecto detecta:",
    ["Anticorpos livres no soro", "Plaquetas", "Fibrinogénio", "Hemoglobina livre"], 0,
    "Pesquisa anticorpos irregulares circulantes."),
  q("lby39", "Imunohematologia", "Conservação do concentrado de hemácias:",
    ["Temperatura ambiente", "2-6 °C", "-20 °C", "37 °C"], 1,
    "Refrigeração entre 2 e 6 °C."),
  q("lby40", "Imunohematologia", "Plasma fresco congelado conserva-se a:",
    ["2-6 °C", "≤ -18 °C", "20-25 °C", "37 °C"], 1,
    "PFC: congelado a ≤ -18 °C."),
  q("lby41", "Parasitologia", "Método de Kato-Katz pesquisa:",
    ["Plasmodium", "Ovos de helmintos (Schistosoma, Ascaris)", "Bactérias", "Vírus"], 1,
    "Quantitativo para ovos de helmintos nas fezes."),
  q("lby42", "Parasitologia", "Tripanossomíase africana - diagnóstico:",
    ["Hemograma", "Pesquisa do parasita em sangue/LCR", "Urocultura", "Coprocultura"], 1,
    "Trypanosoma brucei no sangue ou LCR."),
  q("lby43", "Parasitologia", "Giardia lamblia diagnostica-se por:",
    ["Hemocultura", "Exame parasitológico de fezes", "Urina tipo II", "PCR HIV"], 1,
    "EPF com pesquisa de cistos/trofozoítos."),
  q("lby44", "Imunologia", "Teste de ELISA detecta:",
    ["Glicose", "Antígenos/anticorpos específicos", "Hemácias", "Plaquetas"], 1,
    "Imunoensaio enzimático."),
  q("lby45", "Imunologia", "Janela imunológica do HIV refere-se a:",
    ["Período entre infecção e detecção de anticorpos", "Cura espontânea", "Resistência viral", "Imunidade vacinal"], 0,
    "Tempo até serologia tornar-se positiva."),
  q("lby46", "Urinálise", "Densidade urinária normal:",
    ["1.000-1.005", "1.010-1.030", "1.040-1.060", ">1.080"], 1,
    "Densidade habitual em adulto."),
  q("lby47", "Urinálise", "Cilindros hemáticos sugerem:",
    ["ITU baixa", "Glomerulonefrite", "Desidratação", "Cistite"], 1,
    "Origem glomerular."),
  q("lby48", "Biossegurança", "EPI mínimo para colheita de sangue:",
    ["Nada", "Luvas", "Luvas, jaleco e óculos quando indicado", "Apenas máscara"], 2,
    "Precauções padrão para fluidos corporais."),
  q("lby49", "Biossegurança", "Descarte de agulhas faz-se em:",
    ["Saco preto", "Caixa rígida amarela (perfurocortantes)", "Lixo comum", "Saco azul"], 1,
    "Recipiente rígido específico."),
  q("lby50", "Qualidade", "Controlo interno da qualidade visa:",
    ["Calibrar uma vez por ano", "Monitorizar precisão e exactidão diárias", "Aumentar custos", "Substituir o técnico"], 1,
    "CIQ avalia desempenho analítico contínuo."),
];
