import { Question } from "./concursos";

const q = (
  id: string, disciplina: string, enunciado: string,
  opcoes: string[], correta: number, comentario: string,
): Question => ({ id, disciplina, enunciado, opcoes, correta, comentario });

// Banco Médico expandido (MINSA 2026)
export const bancoMedico: Question[] = [
  q("md1", "Saúde Pública", "Principal causa de mortalidade infantil em Angola:",
    ["Diarreia", "Malária", "Pneumonia", "Desnutrição"], 1,
    "A malária permanece como principal causa de mortalidade infantil em Angola."),
  q("md2", "Clínica Médica", "Tratamento de 1.ª linha para malária grave:",
    ["Cloroquina oral", "Artesunato EV", "Quinino oral", "Mefloquina"], 1,
    "OMS/MINSA: Artesunato endovenoso é a 1.ª linha na malária grave."),
  q("md3", "Pediatria", "1.ª dose da vacina contra sarampo no PAV de Angola:",
    ["6 meses", "9 meses", "12 meses", "15 meses"], 1,
    "PAV Angola: 1.ª dose aos 9 meses."),
  q("md4", "Saúde Pública", "Agente etiológico da tuberculose:",
    ["M. bovis", "M. tuberculosis", "M. leprae", "M. avium"], 1,
    "Mycobacterium tuberculosis é o agente principal da TB pulmonar."),
  q("md5", "Saúde Pública", "Critério diagnóstico de febre tifóide:",
    ["TR malária+", "Hemocultura para Salmonella typhi", "PCR HIV", "BK na expectoração"], 1,
    "O padrão-ouro é a hemocultura positiva para S. typhi."),
  q("md6", "Saúde Pública", "Vector da cólera:",
    ["Mosquito", "Água/alimentos contaminados por Vibrio cholerae", "Carraça", "Aerossol"], 1,
    "Transmissão fecal-oral por água/alimentos contaminados."),
  q("md7", "Medicina Interna", "Diabetes Mellitus tipo 1 caracteriza-se por:",
    ["Resistência à insulina", "Destruição auto-imune das células β", "Excesso de cortisol", "Hipotiroidismo"], 1,
    "DM1: destruição auto-imune das células beta pancreáticas."),
  q("md8", "Medicina Interna", "HbA1c diagnóstica de DM:",
    ["≥ 5,7%", "≥ 6,0%", "≥ 6,5%", "≥ 7,0%"], 2,
    "HbA1c ≥ 6,5% confirma diabetes."),
  q("md9", "Medicina Interna", "HTA estádio 2 (JNC):",
    ["≥130/80", "≥140/90", "≥160/100", "≥180/120"], 2,
    "Estádio 2: TAS ≥160 ou TAD ≥100 mmHg."),
  q("md10", "Medicina Interna", "Critério de diálise de urgência:",
    ["Hipernatremia leve", "Hipercaliemia refractária / EAP urémico", "Anemia leve", "Proteinúria"], 1,
    "Indicações: acidose, hipercaliemia refractária, EAP urémico, uremia sintomática."),
  q("md11", "Medicina Interna", "Asma: critério de gravidade:",
    ["FEV1 >80%", "FEV1 <60% pós-broncodilatador", "FEF25-75 normal", "Tosse seca"], 1,
    "FEV1 <60% indica asma grave."),
  q("md12", "Medicina Interna", "Classe funcional NYHA III:",
    ["Sem limitação", "Sintomas em grandes esforços", "Sintomas em pequenos esforços", "Sintomas em repouso"], 2,
    "NYHA III: dispneia em pequenos esforços."),
  q("md13", "Medicina Interna", "Anemia ferropriva: VCM e CHCM esperados:",
    ["Aumentados", "Normais", "Diminuídos (microcítica hipocrómica)", "Variáveis"], 2,
    "Microcítica hipocrómica: VCM e CHCM baixos."),
  q("md14", "Cirurgia/Trauma", "Tríade de Beck (tamponamento cardíaco):",
    ["Hipotensão, ingurgitamento jugular, abafamento de bulhas", "Febre, dor, taquicardia", "Cianose, dispneia, sibilos", "Bradicardia, midríase, apneia"], 0,
    "Sinais clássicos do tamponamento: hipotensão, jugulares túrgidas, bulhas abafadas."),
  q("md15", "Cirurgia/Trauma", "Choque hipovolémico classe III (ATLS):",
    ["<15% volemia", "15-30%", "30-40%", ">40%"], 2,
    "Classe III: 30-40% perda volémica, taquicardia e hipotensão."),
  q("md16", "Cirurgia/Trauma", "Sinal de Cullen sugere:",
    ["Apendicite", "Pancreatite hemorrágica", "Colecistite", "Diverticulite"], 1,
    "Cullen periumbilical e Grey-Turner em flancos: hemorragia retroperitoneal."),
  q("md17", "G&O", "Hemorragia do 3.º trimestre - causa mais frequente:",
    ["Aborto", "Placenta prévia / DPP", "Pólipos", "Mola"], 1,
    "Causas principais: placenta prévia e descolamento prematuro de placenta."),
  q("md18", "G&O", "Pré-eclâmpsia grave inclui:",
    ["TA ≥120/80", "TA ≥160/110 + proteinúria/lesão de órgão", "Edema isolado", "Glicosúria"], 1,
    "Critérios graves: TA ≥160/110 ou disfunção orgânica."),
  q("md19", "Pediatria", "Reanimação neonatal: 1.º passo após nascimento:",
    ["Massagem cardíaca", "Aquecer, secar, posicionar, aspirar e estimular", "Adrenalina", "Intubar"], 1,
    "Passos iniciais (Golden Minute) antes de ventilar."),
  q("md20", "Pediatria", "Vacina BCG - via:",
    ["IM", "SC", "ID", "EV"], 2,
    "BCG é aplicada por via intradérmica no deltóide direito."),
  q("md21", "Saúde Pública", "Coma de Glasgow ≤8 sugere:",
    ["Coma leve", "Necessidade de IOT (via aérea)", "Alta hospitalar", "Reflexo normal"], 1,
    "GCS ≤8 indica coma e necessidade de protecção da via aérea."),
  q("md22", "Hematologia", "Anemia falciforme: tratamento de base que reduz crises:",
    ["Sulfato ferroso", "Hidroxiureia", "Vitamina C", "Penicilina"], 1,
    "Hidroxiureia aumenta HbF e reduz crises vaso-oclusivas."),
  q("md23", "Saúde Pública", "Lei de Bases do SNS de Angola:",
    ["Lei 21-B/92", "Lei 11/02", "Lei 1/00", "Decreto 5/87"], 0,
    "Lei 21-B/92 estabelece o SNS de Angola."),
  q("md24", "Cultura Geral", "Censo Populacional de Angola 2024 - órgão executor:",
    ["MINSA", "INE", "INSS", "MAT"], 1,
    "Instituto Nacional de Estatística (INE) coordena o Censo."),
  q("md25", "Ética", "Sigilo médico pode ser quebrado em:",
    ["Curiosidade do colega", "Notificação compulsória / ordem judicial", "Pedido familiar", "Convite académico"], 1,
    "Doenças de notificação obrigatória e ordem judicial são excepções legais."),
  q("md26", "Saúde Pública", "Terapêutica anti-retroviral inicial recomendada (1.ª linha) Angola:",
    ["AZT+3TC+NVP", "TDF+3TC+DTG", "EFV+ABC+ddI", "Monoterapia AZT"], 1,
    "1.ª linha actual: TDF+3TC(ou FTC)+DTG."),
  q("md27", "Medicina Interna", "Insulina de acção rápida:",
    ["NPH", "Glargina", "Regular / Lispro", "Detemir"], 2,
    "Insulinas regular, lispro, aspart e glulisina têm acção rápida/ultra-rápida."),
  q("md28", "G&O", "Eclâmpsia: fármaco de eleição para convulsões:",
    ["Diazepam", "Sulfato de magnésio EV", "Fenitoína", "Levetiracetam"], 1,
    "Sulfato de magnésio é a 1.ª escolha (Zuspan/Pritchard)."),
  q("md29", "Pediatria", "Definição de baixo peso ao nascer:",
    ["<3000 g", "<2500 g", "<2000 g", "<1500 g"], 1,
    "OMS: BPN é peso ao nascer <2500 g."),
  q("md30", "Saúde Pública", "Tratamento da TB sensível em adulto - fase intensiva:",
    ["2 meses RHZE", "6 meses RH", "9 meses HE", "1 mês RZ"], 0,
    "Esquema: 2 meses RHZE + 4 meses RH (esquema básico)."),
];

// Banco Laboratório expandido
export const bancoLab: Question[] = [
  q("lb1", "Hematologia", "Hematócrito normal masculino:", ["20-30%", "30-38%", "40-54%", "55-65%"], 2, "Adulto masculino: 40-54%."),
  q("lb2", "Hematologia", "Anemia segundo OMS - mulher adulta:", ["Hb<13", "Hb<12", "Hb<10", "Hb<8"], 1, "Mulher: Hb<12 g/dL; homem: <13 g/dL."),
  q("lb3", "Microbiologia", "Coloração de Ziehl-Neelsen identifica:", ["Gram+", "BAAR", "Fungos", "Vírus"], 1, "Bacilos álcool-ácido resistentes (TB)."),
  q("lb4", "Microbiologia", "Coloração de Gram - cor dos Gram positivos:", ["Rosa", "Azul/violeta", "Verde", "Castanho"], 1, "Gram+ retêm cristal violeta (azul/violeta)."),
  q("lb5", "Bioquímica", "Glicemia em jejum normal:", ["<70", "70-99", "100-125", "≥126"], 1, "Normal: 70-99 mg/dL."),
  q("lb6", "Bioquímica", "Creatinina aumentada indica:", ["Função hepática", "Função renal alterada", "Anemia", "Infecção"], 1, "Marcador de função renal."),
  q("lb7", "Imunohematologia", "Doador universal de hemácias:", ["A+", "AB+", "O-", "B-"], 2, "O negativo é doador universal de concentrado de hemácias."),
  q("lb8", "Imunohematologia", "Receptor universal de plasma:", ["O", "A", "B", "AB"], 0, "Plasma de AB é doador universal; receptor universal de plasma é O."),
  q("lb9", "Parasitologia", "Diagnóstico parasitológico de malária padrão-ouro:", ["TR", "Gota espessa + esfregaço", "PCR rotina", "Soro"], 1, "Gota espessa corada por Giemsa."),
  q("lb10", "Hematologia", "INR alvo em anticoagulação para FA:", ["1-1,5", "2-3", "3-4", "4-5"], 1, "Alvo terapêutico padrão: INR 2-3."),
  q("lb11", "Bioquímica", "TGP (ALT) elevada sugere lesão de:", ["Coração", "Fígado", "Pâncreas", "Rim"], 1, "ALT é marcador hepatocelular."),
  q("lb12", "Microbiologia", "Meio de cultura para Mycobacterium tuberculosis:", ["MacConkey", "Löwenstein-Jensen", "Sabouraud", "Ágar sangue"], 1, "Löwenstein-Jensen é o meio clássico."),
];

// Banco Fisioterapia expandido
export const bancoFisio: Question[] = [
  q("ft1", "Cinesiologia", "Principal flexor do cotovelo:", ["Tríceps", "Bíceps braquial", "Deltóide", "Coracobraquial"], 1, "Bíceps braquial."),
  q("ft2", "Reabilitação", "Reabilitação pós-AVC deve iniciar:", ["1 mês depois", "Após estabilização clínica", "Após alta", "6 meses depois"], 1, "Início precoce melhora prognóstico."),
  q("ft3", "Avaliação", "Escala de Ashworth modificada avalia:", ["Dor", "Espasticidade", "Força", "Equilíbrio"], 1, "Avalia tónus/espasticidade."),
  q("ft4", "Avaliação", "Escala de Barthel mede:", ["Dor", "AVD", "Força", "Cognição"], 1, "Independência nas AVD."),
  q("ft5", "Reabilitação", "Amputado transtibial - fase pré-protetização inclui:", ["Imobilização total", "Modelagem do coto e fortalecimento", "Repouso absoluto", "Cirurgia"], 1, "Modelagem com bandagem em 8, fortalecimento e mobilização articular."),
  q("ft6", "Cinesiologia", "ADM normal flexão do ombro:", ["90°", "120°", "180°", "60°"], 2, "Aproximadamente 180° de flexão."),
  q("ft7", "Reabilitação cardio-respiratória", "Drenagem postural visa:", ["Aumentar tosse", "Mobilizar secreções", "Reduzir dor", "Aumentar FC"], 1, "Posicionamento para mobilizar secreções por gravidade."),
  q("ft8", "Órteses", "Órtese AFO é usada em:", ["Pé equino", "Escoliose", "Luxação ombro", "Lombalgia"], 0, "Ankle-Foot Orthosis corrige queda do pé."),
];

// Banco Cardiopneumologia expandido
export const bancoCardio: Question[] = [
  q("cp1", "ECG", "Onda P representa:", ["Despolarização ventricular", "Repolarização V", "Despolarização auricular", "Repolarização A"], 2, "Onda P = despolarização auricular."),
  q("cp2", "ECG", "Intervalo PR normal:", ["0,06-0,10s", "0,12-0,20s", "0,20-0,30s", ">0,30s"], 1, "PR normal: 120-200 ms."),
  q("cp3", "ECG", "FA caracteriza-se por:", ["Ondas P regulares", "Ausência de P + RR irregular", "QRS alargado", "ST elevado"], 1, "Sem ondas P, RR irregular."),
  q("cp4", "Função Pulmonar", "VEF1/CVF <70% indica:", ["Restritivo", "Obstrutivo", "Normal", "Atelectasia"], 1, "Padrão obstrutivo (DPOC, asma)."),
  q("cp5", "Função Pulmonar", "Padrão restritivo: redução de:", ["VEF1/CVF", "CVF com índice normal", "PEF apenas", "FR"], 1, "Restritivo: CVF baixa, índice normal/aumentado."),
  q("cp6", "ECG", "Supradesnivelamento de ST sugere:", ["Pericardite/IAM", "Hipocaliemia", "BAV", "Bloqueio de ramo"], 0, "STEMI ou pericardite."),
  q("cp7", "Vascular", "Doppler venoso avalia:", ["Espessura óssea", "Trombose venosa profunda", "Função renal", "Densidade pulmonar"], 1, "DVP no diagnóstico de TVP."),
];

// Banco Psicologia expandido
export const bancoPsi: Question[] = [
  q("ps1", "Psicopatologia", "Depressão major DSM-5 - duração mínima:", ["1 sem", "2 sem", "1 mês", "3 meses"], 1, "Mínimo 2 semanas."),
  q("ps2", "Psicologia da Saúde", "Modelo biopsicossocial integra:", ["Só biológico", "Bio+psico+social", "Só social", "Espiritual"], 1, "Engel, 1977."),
  q("ps3", "Ética", "Consentimento informado deve ser:", ["Verbal", "Tácito", "Documentado e esclarecido", "Dispensável"], 2, "Documentado e esclarecido."),
  q("ps4", "Psicopatologia", "Esquizofrenia - sintoma positivo:", ["Embotamento", "Alucinação", "Anedonia", "Apatia"], 1, "Positivos: alucinações, delírios."),
  q("ps5", "Avaliação", "Mini-Mental avalia:", ["Humor", "Cognição", "Personalidade", "Inteligência"], 1, "Rastreio cognitivo (MEEM)."),
  q("ps6", "Psicopatologia", "Transtorno de pânico caracteriza-se por:", ["Tristeza crónica", "Crises súbitas de medo intenso", "Compulsões", "Apatia"], 1, "Crises agudas com sintomas autonómicos."),
];
