// Generates two artifacts from the full quiz source (kept ONLY in
// supabase/functions/_shared/_source, never bundled into the client):
//
//   1. supabase/functions/_shared/quiz-bank.json  — FULL data incl. correct
//      answers + comments. Served by the gated `quiz-content` edge function.
//   2. src/data/concursos.ts                       — PUBLIC data with `correta`
//      set to -1 and `comentario` emptied, so the answer key never ships in the
//      browser JavaScript bundle.
//
// Run with:  bun run scripts/generate-quiz-bank.ts
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { concursos } from "../supabase/functions/_shared/_source/concursos.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// 1. Full bank for the server.
const bankPath = resolve(root, "supabase/functions/_shared/quiz-bank.json");
mkdirSync(dirname(bankPath), { recursive: true });
writeFileSync(bankPath, JSON.stringify(concursos), "utf8");

// 2. Stripped, self-contained client module.
const stripped = concursos.map((c) => ({
  ...c,
  categorias: c.categorias.map((cat) => ({
    ...cat,
    questoes: cat.questoes.map((q) => ({ ...q, correta: -1, comentario: "" })),
  })),
}));

const header = `// AUTO-GENERATED by scripts/generate-quiz-bank.ts — DO NOT EDIT BY HAND.
// The correct answers (\`correta\`) and explanations (\`comentario\`) are
// intentionally stripped here so they never reach the client bundle. They are
// served on demand by the gated \`quiz-content\` edge function to users who have
// trial or paid access. Edit the source under
// supabase/functions/_shared/_source and re-run the generator.

export type Question = {
  id: string;
  enunciado: string;
  opcoes: string[];
  correta: number;
  comentario: string;
  disciplina: string;
};

export type Topico = { titulo: string; itens: string[] };

export type Categoria = {
  id: string;
  nome: string;
  descricao: string;
  icon: string;
  disciplinas: string[];
  questoes: Question[];
  topicos?: Topico[];
};

export type Concurso = {
  id: string;
  nome: string;
  sigla: string;
  area: string;
  descricao: string;
  ano: string;
  inscricaoUrl?: string;
  documentosInscricao?: string[];
  categorias: Categoria[];
};

export const concursos: Concurso[] = ${JSON.stringify(stripped, null, 2)};

export const getConcurso = (id: string) => concursos.find((c) => c.id === id);
export const getCategoria = (concursoId: string, catId: string) =>
  getConcurso(concursoId)?.categorias.find((c) => c.id === catId);
`;

writeFileSync(resolve(root, "src/data/concursos.ts"), header, "utf8");

console.log("Generated quiz-bank.json and stripped src/data/concursos.ts");
